create_combined_catalog:
	php ../../src/Auxilary/converter_straglr2methylartist.php -catalog ../repeat_expansions/straglr_variant_catalog_grch38.bed -imprinting_tsv methylartist_catalog_grch38_imprinting_only.tsv -out methylartist_catalog_grch38.tsv
