help:
	@cat Makefile

download:
	#Manual download via browser, because wget returns 403 error:
	#- https://s3.amazonaws.com/igv.org.genomes/hg38/annotations/cytoBandIdeo.txt.gz
	#- https://s3.amazonaws.com/igv.org.genomes/hg38/hg38_alias.tab